general:
  logging:
    console:
      _type: console
      level: WARN

  front_end:
    _type: fastapi

  front_end:
    _type: console

workflow:
  _type: car_maintenance
  parameter: default_value